<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("counsellor");
$id=currentUserId();$message="";$error="";
if($_SERVER["REQUEST_METHOD"]==="POST"){
    $aid=(int)($_POST["appointment_id"]??0);$status=$_POST["status"]??"";
    $allowed=["confirmed","rejected","completed","pending"];
    if(!in_array($status,$allowed,true))$error="Invalid status.";else{
        $stmt=$conn->prepare("SELECT student_id FROM appointments WHERE id=? AND counsellor_id=?");$stmt->bind_param("ii",$aid,$id);$stmt->execute();$a=$stmt->get_result()->fetch_assoc();$stmt->close();
        if(!$a)$error="Appointment not found.";else{$stmt=$conn->prepare("UPDATE appointments SET status=?,updated_at=NOW() WHERE id=? AND counsellor_id=?");$stmt->bind_param("sii",$status,$aid,$id);$stmt->execute();$stmt->close();$title="Appointment updated";$msg="Your appointment status is now ".str_replace("_"," ",$status)."."; $stmt=$conn->prepare("INSERT INTO notifications(user_id,appointment_id,title,message) VALUES(?,?,?,?)");$stmt->bind_param("iiss",$a["student_id"],$aid,$title,$msg);$stmt->execute();$stmt->close();$message="Appointment updated.";}
    }
}
$stmt=$conn->prepare("SELECT a.id,a.status,a.student_id,s.full_name student_name,sl.appointment_date,sl.start_time,sl.end_time FROM appointments a JOIN users s ON a.student_id=s.id JOIN appointment_slots sl ON a.slot_id=sl.id WHERE a.counsellor_id=? ORDER BY sl.appointment_date DESC,sl.start_time DESC");$stmt->bind_param("i",$id);$stmt->execute();$appointments=$stmt->get_result();$stmt->close();
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Counsellor Appointments</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><h1>Counsellor Appointments</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><div class="card table-responsive"><table><tr><th>Student</th><th>Date</th><th>Time</th><th>Status</th><th>Action</th></tr><?php foreach($appointments as $a): ?><tr><td><?php echo htmlspecialchars($a["student_name"]); ?></td><td><?php echo htmlspecialchars($a["appointment_date"]); ?></td><td><?php echo htmlspecialchars(date("H:i",strtotime($a["start_time"]))." - ".date("H:i",strtotime($a["end_time"]))); ?></td><td><?php echo htmlspecialchars($a["status"]); ?></td><td><form method="POST"><input type="hidden" name="appointment_id" value="<?php echo $a["id"]; ?>"><select name="status"><option value="pending">Pending</option><option value="confirmed">Confirm</option><option value="rejected">Reject</option><option value="completed">Complete</option></select><button class="btn btn-small">Update</button></form></td></tr><?php endforeach; ?></table></div><p><a href="dashboard.php">Back</a></p></main></body></html>