<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("admin");
$message="";$error="";
if($_SERVER["REQUEST_METHOD"]==="POST"&&isset($_POST["update_status"])){
 $aid=(int)$_POST["appointment_id"];$status=$_POST["status"];
 $allowed=["pending","confirmed","cancelled","reschedule_requested","completed","rejected"];
 if(!in_array($status,$allowed,true))$error="Invalid appointment status.";else{$stmt=$conn->prepare("UPDATE appointments SET status=?,updated_at=NOW() WHERE id=?");$stmt->bind_param("si",$status,$aid);$stmt->execute();$stmt->close();$message="Appointment status updated.";}
}
$a=$conn->query("SELECT a.id,a.status,a.created_at,s.full_name student_name,s.email student_email,c.full_name counsellor_name,sl.appointment_date,sl.start_time,sl.end_time FROM appointments a JOIN users s ON a.student_id=s.id JOIN users c ON a.counsellor_id=c.id JOIN appointment_slots sl ON a.slot_id=sl.id ORDER BY sl.appointment_date DESC,sl.start_time DESC");
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appointment Management</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><h1>Appointment Management</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><div class="card table-responsive"><table><tr><th>Student</th><th>Counsellor</th><th>Date</th><th>Time</th><th>Status</th><th>Action</th></tr><?php foreach($a as $r): ?><tr><td><?php echo htmlspecialchars($r["student_name"]); ?><br><small><?php echo htmlspecialchars($r["student_email"]); ?></small></td><td><?php echo htmlspecialchars($r["counsellor_name"]); ?></td><td><?php echo htmlspecialchars($r["appointment_date"]); ?></td><td><?php echo htmlspecialchars(date("H:i",strtotime($r["start_time"]))." - ".date("H:i",strtotime($r["end_time"]))); ?></td><td><?php echo htmlspecialchars($r["status"]); ?></td><td><form method="POST"><input type="hidden" name="appointment_id" value="<?php echo $r["id"]; ?>"><input type="hidden" name="update_status" value="1"><select name="status" onchange="this.form.submit()"><option value="pending" <?php echo $r["status"]==="pending"?"selected":""; ?>>Pending</option><option value="confirmed" <?php echo $r["status"]==="confirmed"?"selected":""; ?>>Confirmed</option><option value="cancelled" <?php echo $r["status"]==="cancelled"?"selected":""; ?>>Cancelled</option><option value="reschedule_requested" <?php echo $r["status"]==="reschedule_requested"?"selected":""; ?>>Reschedule Requested</option><option value="completed" <?php echo $r["status"]==="completed"?"selected":""; ?>>Completed</option><option value="rejected" <?php echo $r["status"]==="rejected"?"selected":""; ?>>Rejected</option></select></form></td></tr><?php endforeach; ?></table></div><p><a href="dashboard.php">Back</a></p></main></body></html>