<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("admin");
$message="";$error="";
if($_SERVER["REQUEST_METHOD"]==="POST"&&isset($_POST["update_status"])){
 $uid=(int)$_POST["user_id"];$status=$_POST["status"];
 if(!in_array($status,["active","inactive","suspended"],true))$error="Invalid status.";else{$stmt=$conn->prepare("UPDATE users SET status=?,updated_at=NOW() WHERE id=? AND role='counsellor'");$stmt->bind_param("si",$status,$uid);$stmt->execute();$stmt->close();$message="Counsellor status updated.";}
}
$c=$conn->query("SELECT u.id,u.full_name,u.email,u.phone,u.status,u.created_at,cp.specialization,cp.bio FROM users u LEFT JOIN counsellor_profiles cp ON u.id=cp.user_id WHERE u.role='counsellor' ORDER BY u.created_at DESC");
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Counsellors</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><h1>Counsellor Management</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><div class="card table-responsive"><table><tr><th>Name</th><th>Email</th><th>Phone</th><th>Specialization</th><th>Status</th><th>Action</th></tr><?php foreach($c as $r): ?><tr><td><?php echo htmlspecialchars($r["full_name"]); ?></td><td><?php echo htmlspecialchars($r["email"]); ?></td><td><?php echo htmlspecialchars($r["phone"]??"-"); ?></td><td><?php echo htmlspecialchars($r["specialization"]??"Not specified"); ?></td><td><?php echo htmlspecialchars($r["status"]); ?></td><td><form method="POST"><input type="hidden" name="user_id" value="<?php echo $r["id"]; ?>"><input type="hidden" name="update_status" value="1"><select name="status" onchange="this.form.submit()"><option value="active" <?php echo $r["status"]==="active"?"selected":""; ?>>Active</option><option value="inactive" <?php echo $r["status"]==="inactive"?"selected":""; ?>>Inactive</option><option value="suspended" <?php echo $r["status"]==="suspended"?"selected":""; ?>>Suspended</option></select></form></td></tr><?php endforeach; ?></table></div><p><a href="dashboard.php">Back</a></p></main></body></html>