<?php
require_once "../includes/config.php"; require_once "../includes/auth.php"; requireRole("student");
$id=currentUserId();
$stmt=$conn->prepare("SELECT full_name FROM users WHERE id=?"); $stmt->bind_param("i",$id); $stmt->execute(); $user=$stmt->get_result()->fetch_assoc(); $stmt->close();
$stmt=$conn->prepare("SELECT COUNT(*) total FROM appointments WHERE student_id=? AND status IN('pending','confirmed','reschedule_requested')"); $stmt->bind_param("i",$id); $stmt->execute(); $active=$stmt->get_result()->fetch_assoc()["total"]; $stmt->close();
$slots=$conn->query("SELECT COUNT(*) total FROM appointment_slots WHERE status='available' AND appointment_date>=CURDATE()")->fetch_assoc()["total"];
$stmt=$conn->prepare("SELECT a.status,sl.appointment_date,sl.start_time,c.full_name counsellor FROM appointments a JOIN appointment_slots sl ON a.slot_id=sl.id JOIN users c ON a.counsellor_id=c.id WHERE a.student_id=? ORDER BY a.created_at DESC LIMIT 5"); $stmt->bind_param("i",$id); $stmt->execute(); $recent=$stmt->get_result(); $stmt->close();
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Dashboard</title><link rel="stylesheet" href="../assets/css/style.css"></head><body>
<header class="navbar"><div class="container nav-content"><a class="logo" href="../index.php">Chebara Counselling</a><nav class="nav-links"><a href="dashboard.php">Dashboard</a><a href="book.php">Book</a><a href="appointments.php">Appointments</a><a href="profile.php">Profile</a><a href="../notifications.php">Notifications</a><a href="../logout.php">Logout</a></nav></div></header>
<main class="container"><section class="dashboard-header"><h1>Student Dashboard</h1><p>Welcome, <?php echo htmlspecialchars($user["full_name"]); ?>.</p></section>
<section class="dashboard-grid"><div class="card"><h3>Active Appointments</h3><p class="stat-number"><?php echo $active; ?></p></div><div class="card"><h3>Available Slots</h3><p class="stat-number"><?php echo $slots; ?></p></div></section>
<div class="card"><h2>Recent Appointments</h2><?php if($recent->num_rows): ?><div class="table-responsive"><table><tr><th>Counsellor</th><th>Date</th><th>Time</th><th>Status</th></tr><?php foreach($recent as $r): ?><tr><td><?php echo htmlspecialchars($r["counsellor"]); ?></td><td><?php echo htmlspecialchars($r["appointment_date"]); ?></td><td><?php echo htmlspecialchars(date("H:i",strtotime($r["start_time"]))); ?></td><td><?php echo htmlspecialchars($r["status"]); ?></td></tr><?php endforeach; ?></table></div><?php else: ?><p>No appointments yet.</p><?php endif; ?></div></main></body></html>