<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("admin");
$id=currentUserId();$stmt=$conn->prepare("SELECT full_name FROM users WHERE id=?");$stmt->bind_param("i",$id);$stmt->execute();$admin=$stmt->get_result()->fetch_assoc();$stmt->close();
$student_count=$conn->query("SELECT COUNT(*) total FROM users WHERE role='student'")->fetch_assoc()["total"];
$counsellor_count=$conn->query("SELECT COUNT(*) total FROM users WHERE role='counsellor'")->fetch_assoc()["total"];
$appointment_count=$conn->query("SELECT COUNT(*) total FROM appointments")->fetch_assoc()["total"];
$pending_count=$conn->query("SELECT COUNT(*) total FROM appointments WHERE status='pending'")->fetch_assoc()["total"];
$available_slots=$conn->query("SELECT COUNT(*) total FROM appointment_slots WHERE status='available' AND appointment_date>=CURDATE()")->fetch_assoc()["total"];
$recent=$conn->query("SELECT a.status,s.full_name student_name,c.full_name counsellor_name,sl.appointment_date,sl.start_time,sl.end_time FROM appointments a JOIN users s ON a.student_id=s.id JOIN users c ON a.counsellor_id=c.id JOIN appointment_slots sl ON a.slot_id=sl.id ORDER BY a.created_at DESC LIMIT 8");
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Dashboard</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><header class="navbar"><div class="container nav-content"><a class="logo" href="../index.php">Chebara Counselling</a><nav class="nav-links"><a href="dashboard.php">Dashboard</a><a href="users.php">Users</a><a href="counsellors.php">Counsellors</a><a href="appointments.php">Appointments</a><a href="reports.php">Reports</a><a href="settings.php">Settings</a><a href="../logout.php">Logout</a></nav></div></header><main class="container"><section class="dashboard-header"><h1>Admin Dashboard</h1><p>Welcome, <?php echo htmlspecialchars($admin["full_name"]); ?>.</p></section><section class="dashboard-grid"><div class="card"><h3>Students</h3><p class="stat-number"><?php echo $student_count; ?></p></div><div class="card"><h3>Counsellors</h3><p class="stat-number"><?php echo $counsellor_count; ?></p></div><div class="card"><h3>Appointments</h3><p class="stat-number"><?php echo $appointment_count; ?></p></div><div class="card"><h3>Pending</h3><p class="stat-number"><?php echo $pending_count; ?></p></div><div class="card"><h3>Available Slots</h3><p class="stat-number"><?php echo $available_slots; ?></p></div></section><div class="card"><h2>Recent Appointments</h2><div class="table-responsive"><table><tr><th>Student</th><th>Counsellor</th><th>Date</th><th>Time</th><th>Status</th></tr><?php foreach($recent as $r): ?><tr><td><?php echo htmlspecialchars($r["student_name"]); ?></td><td><?php echo htmlspecialchars($r["counsellor_name"]); ?></td><td><?php echo htmlspecialchars($r["appointment_date"]); ?></td><td><?php echo htmlspecialchars(date("H:i",strtotime($r["start_time"]))." - ".date("H:i",strtotime($r["end_time"]))); ?></td><td><?php echo htmlspecialchars($r["status"]); ?></td></tr><?php endforeach; ?></table></div></div></main></body></html>