<?php
require_once "../includes/config.php"; require_once "../includes/auth.php"; requireRole("student");
$id=currentUserId(); $message=""; $error="";
if($_SERVER["REQUEST_METHOD"]==="POST"){
    $name=trim($_POST["full_name"]??"");$phone=trim($_POST["phone"]??"");
    if($name==="")$error="Name is required."; else{$stmt=$conn->prepare("UPDATE users SET full_name=?,phone=?,updated_at=NOW() WHERE id=? AND role='student'");$stmt->bind_param("ssi",$name,$phone,$id);if($stmt->execute()){$message="Profile updated.";$_SESSION["full_name"]=$name;}else{$error="Could not update profile.";} $stmt->close();}
}
$stmt=$conn->prepare("SELECT full_name,email,phone FROM users WHERE id=?");$stmt->bind_param("i",$id);$stmt->execute();$user=$stmt->get_result()->fetch_assoc();$stmt->close();
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Profile</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><div class="card"><h1>My Profile</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><form method="POST"><div class="form-group"><label>Full Name</label><input name="full_name" required value="<?php echo htmlspecialchars($user["full_name"]); ?>"></div><div class="form-group"><label>Email</label><input value="<?php echo htmlspecialchars($user["email"]); ?>" disabled></div><div class="form-group"><label>Phone</label><input name="phone" value="<?php echo htmlspecialchars($user["phone"]??""); ?>"></div><button class="btn">Save Changes</button></form><p><a href="dashboard.php">Back to dashboard</a></p></div></main></body></html>