<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("counsellor");
$id=currentUserId();$message="";$error="";
if($_SERVER["REQUEST_METHOD"]==="POST"){
    $action=$_POST["action"]??"";
    if($action==="create"){
        $date=$_POST["appointment_date"]??"";$start=$_POST["start_time"]??"";$end=$_POST["end_time"]??"";
        if($date<date("Y-m-d")||$start===""||$end===""||$end<=$start)$error="Enter a valid future date and time range.";
        else{$stmt=$conn->prepare("INSERT INTO appointment_slots(counsellor_id,appointment_date,start_time,end_time,status) VALUES(?,?,?,?, 'available')");$stmt->bind_param("isss",$id,$date,$start,$end);if($stmt->execute())$message="Slot created.";else $error=$conn->errno===1062?"That slot already exists.":"Could not create slot."; $stmt->close();}
    } elseif($action==="block"||$action==="restore"){
        $slot=(int)($_POST["slot_id"]??0);$status=$action==="block"?"blocked":"available";$stmt=$conn->prepare("UPDATE appointment_slots SET status=? WHERE id=? AND counsellor_id=? AND status IN('available','blocked')");$stmt->bind_param("sii",$status,$slot,$id);$stmt->execute();$stmt->close();$message="Slot updated.";
    }
}
$stmt=$conn->prepare("SELECT id,appointment_date,start_time,end_time,status FROM appointment_slots WHERE counsellor_id=? ORDER BY appointment_date DESC,start_time DESC");$stmt->bind_param("i",$id);$stmt->execute();$slots=$stmt->get_result();$stmt->close();
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manage Slots</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><div class="card"><h1>Appointment Slots</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><form method="POST"><input type="hidden" name="action" value="create"><div class="form-group"><label>Date</label><input type="date" name="appointment_date" min="<?php echo date("Y-m-d"); ?>" required></div><div class="form-group"><label>Start Time</label><input type="time" name="start_time" required></div><div class="form-group"><label>End Time</label><input type="time" name="end_time" required></div><button class="btn">Create Slot</button></form></div><div class="card table-responsive"><table><tr><th>Date</th><th>Time</th><th>Status</th><th>Action</th></tr><?php foreach($slots as $s): ?><tr><td><?php echo htmlspecialchars($s["appointment_date"]); ?></td><td><?php echo htmlspecialchars(date("H:i",strtotime($s["start_time"]))." - ".date("H:i",strtotime($s["end_time"]))); ?></td><td><?php echo htmlspecialchars($s["status"]); ?></td><td><?php if($s["status"]==="available"): ?><form method="POST"><input type="hidden" name="action" value="block"><input type="hidden" name="slot_id" value="<?php echo $s["id"]; ?>"><button class="btn btn-small btn-secondary">Block</button></form><?php elseif($s["status"]==="blocked"): ?><form method="POST"><input type="hidden" name="action" value="restore"><input type="hidden" name="slot_id" value="<?php echo $s["id"]; ?>"><button class="btn btn-small">Restore</button></form><?php else: ?>Booked<?php endif; ?></td></tr><?php endforeach; ?></table></div><p><a href="dashboard.php">Back to dashboard</a></p></main></body></html>