<?php
require_once "../includes/config.php";require_once "../includes/auth.php";requireRole("admin");
$message="";$error="";
if($_SERVER["REQUEST_METHOD"]==="POST"&&isset($_POST["update_status"])){
 $uid=(int)$_POST["user_id"];$status=$_POST["status"];
 if(!in_array($status,["active","inactive","suspended"],true))$error="Invalid status.";
 elseif($uid===currentUserId())$error="You cannot change your own status.";
 else{$stmt=$conn->prepare("UPDATE users SET status=?,updated_at=NOW() WHERE id=?");$stmt->bind_param("si",$status,$uid);$stmt->execute();$stmt->close();$message="User status updated.";}
}
$search=trim($_GET["search"]??"");
if($search!==""){$q="%$search%";$stmt=$conn->prepare("SELECT id,full_name,email,phone,role,status,created_at FROM users WHERE full_name LIKE ? OR email LIKE ? OR phone LIKE ? ORDER BY created_at DESC");$stmt->bind_param("sss",$q,$q,$q);$stmt->execute();$users=$stmt->get_result();}else{$users=$conn->query("SELECT id,full_name,email,phone,role,status,created_at FROM users ORDER BY created_at DESC");}
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>User Management</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container section"><h1>User Management</h1><?php if($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?><div class="card"><form method="GET"><div class="form-group"><label>Search</label><input name="search" value="<?php echo htmlspecialchars($search); ?>" placeholder="Name, email or phone"></div><button class="btn">Search</button> <a class="btn btn-secondary" href="users.php">Clear</a></form></div><div class="card table-responsive"><table><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th><th>Status</th><th>Action</th></tr><?php foreach($users as $u): ?><tr><td><?php echo htmlspecialchars($u["full_name"]); ?></td><td><?php echo htmlspecialchars($u["email"]); ?></td><td><?php echo htmlspecialchars($u["phone"]??"-"); ?></td><td><?php echo htmlspecialchars($u["role"]); ?></td><td><?php echo htmlspecialchars($u["status"]); ?></td><td><?php if($u["id"]==currentUserId()): ?>Current Admin<?php else: ?><form method="POST"><input type="hidden" name="user_id" value="<?php echo $u["id"]; ?>"><input type="hidden" name="update_status" value="1"><select name="status" onchange="this.form.submit()"><option value="active" <?php echo $u["status"]==="active"?"selected":""; ?>>Active</option><option value="inactive" <?php echo $u["status"]==="inactive"?"selected":""; ?>>Inactive</option><option value="suspended" <?php echo $u["status"]==="suspended"?"selected":""; ?>>Suspended</option></select></form><?php endif; ?></td></tr><?php endforeach; ?></table></div><p><a href="dashboard.php">Back to dashboard</a></p></main></body></html>